<Project Sdk="Microsoft.NET.Sdk">


	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		<IgnoreBuildErrors>true</IgnoreBuildErrors>
		<ContinueOnError>true</ContinueOnError>
	</PropertyGroup>

	<ItemGroup>
	  <Reference Include="GlowmaskHelper">
	    <HintPath>..\ModAssemblies\GlowmaskHelper_v1.0.0.dll</HintPath>
	  </Reference>
	  <Reference Include="InnoVault">
	    <HintPath>..\ModAssemblies\InnoVault_v1.9.26.dll</HintPath>
	  </Reference>
	  <Reference Include="OpusLib">
	    <HintPath>..\ModAssemblies\OpusLib_v0.1.1.dll</HintPath>
	  </Reference>
	</ItemGroup>
	

	<!-- References -->

</Project>